name: nerf-env
channels:
- defaults
- conda-forge
dependencies:
        - pytorch>=1.6
        - configargparse
        - matplotlib
        - opencv
        - scikit-image
        - scipy
        - cupy
        - imageio
        - tqdm
        - kornia
